version: 0.2

phases:
  pre_build:
    commands:
      - node -v
      - npm -v
      - npm install -g n
      - node -v
      - npm -v
  build:
    commands:
      - echo Build started on `date`
      - cd my-app
      - npm install
      - npm run build

artifacts:
  files:
    - dist/*
    - appsepc.yml