version: 0.2

phases:
  pre_build:
    commands:
      - node -v
      - npm -v
  build:
    commands:
      - echo Build started on `date`
      - cd my-app
      - npm install
      - npm run build

  post_build:
    commands:
      - ll -a
      - pwd
artifacts:
  files:
    - 'my-app/dist/*'
    - 'appsepc.yml'